let saborEmpanada = prompt("digite el sabor de la empanada")
let cantidadEmpanadas = Number(prompt("digite la cantidad de empanadas"))
let saborGaseosa = prompt ("digite el sabor de su gaseosa")
let cantidadGaseosa = Number (prompt("cantidad de gaseosa"))
let saborPostre = prompt ("digite el sabor de su postre")
let cantidadPostre = Number (prompt("digite la cantidad de postres"))